version: '3'
volumes:
  mysql:
    driver: local
services:
  apache:
    build: .docker/apache
    container_name: wc_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot
    depends_on:
      - php
  mysql:
    image: mysql:8
    container_name: wc_mysql
    ports:
      - 3306:3306
    volumes:
      - .docker/data/db:/var/lib/mysql
      - .docker/provision/mysql/init:/docker-entrypoint-initdb.d
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: wc_password
  php:
    build: .docker/php
    container_name: wc_php
    volumes:
      - .:/home/wwwroot
    depends_on:
      - mysql